config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'games/who_am_i'
  get 'games/teletype'

  get 'cards/generator'
  post 'cards/generated'
  get 'cards/generated', to: redirect('cards/generator')

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users

  get 'celebrities/random'

  # TODO: think up better routing and controller solution for these has_many :through models
  get '/celebrities/:id/answers', to: 'celebrities#answers'
  get '/celebrities/:id/cards', to: 'celebrities#cards'

  # get 'decks/show'
  resources :decks, only: [:show] do
    member do
      get :sorting_game
    end
  end

  # TODO: might want to nest cards within decks
  resources :cards, only: [:show]
  get '/test', to: 'cards#test'

  get '/cards', to: 'decks#featured'
  get '/signup', to: 'users#new'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/random', to: 'cards#random'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :card
  belongs_to :celebrity
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck
  has_many :answers
  has_many :celebrities, through: :answers
  scope :card_ordered, -> { order(face_number: :asc, face_suit: :asc) }
  mount_uploader :image, PictureUploader
  validates :deck_id, presence: true
  validates :lens_name, presence: true, uniqueness: { scope: :deck_id }
end

app/models/celebrity.rb
class Celebrity < ApplicationRecord
  has_many :answers
  has_many :cards, through: :answers
  validates :name, presence: true, uniqueness: true
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :cards, dependent: :destroy

  # returns the featured deck
  # NOTE: currently ok this way as decks must be created manually
  # but need to change this once more decks can be created through web
  def self.featured
    self.last
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness:  { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def test
    @card = Card.order("RANDOM()").first
    render layout: false
  end

  def show
    @card = Card.find(params[:id])
  end

  # Returns a random card
  # Note that this method uses a database call that is NOT DATABASE AGNOSTIC
  # "RANDOM()" should work for postgresql and sqlite
  # Also note that this returns ANY random card, not just any random card belonging to a given deck
  def random
    @card = Card.order("RANDOM()").first
    # Note: Could alternatively redirect to the card show path for the random card
    render 'show'
  end

  def generator
  end

  def generated
    white_cards = params["whitecards"]
    card_size   = params["cardsize"]
    page_layout = params["pagelayout"]
    dpi = params["dpi"].to_i
    email = params["email"]
    background_color = params["background_color"]
    text_color = params["text_color"]
    bleed = params["bleed"]
    background_color = "ffffff" unless background_color.length == 6 and !background_color[/\H/]
    text_color = "000000" unless text_color.length == 6 and !text_color[/\H/]
    pdf = CardPdf.new(white_cards, card_size, page_layout, background_color, text_color, bleed)
    respond_to do |format|
      format.html do
        pdf_file = Rails.root.join('tmp/cards.pdf')
        pdf.render_file pdf_file
        # instead of doing this now, create a job
        # zipfile_name = PdfConverter.create_images pdf_file, dpi, email
        # File.delete(pdf_file) if File.exist?(pdf_file)
        # send_file zipfile_name
        GenerateAndSendPngsJob.perform_later(pdf_file.to_s, dpi, email)
        flash[:success] = "Your generated images will be emailed to the address you provided"
        redirect_to '/cards/generator'
      end
      format.pdf do
        send_data pdf.render,
          filename: "export.pdf",
          type: 'application/pdf',
          disposition: 'inline'
      end
    end
  end
end

app/controllers/celebrities_controller.rb
class CelebritiesController < ApplicationController
  def random
    @celebrities = Celebrity.all
  end

  # This could conceivably be moved to an answers controller
  def answers
    @celebrity = Celebrity.find(params[:id])
    @answers = @celebrity.answers
    render json: @answers
  end

  # TODO: Unclear which controller this controller action should go in.
  def cards
    @celebrity = Celebrity.find(params[:id])
    @cards = @celebrity.cards
    render json: @cards
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController

  def show
    @deck = Deck.find(params[:id])
  end

  def featured
    @deck = Deck.featured
    render 'show'
  end

  def sorting_game
    @deck = Deck.find(params[:id])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def who_am_i
    @deck = Deck.featured
    @celebrities = Celebrity.all
    @card = Card.first
  end

  def teletype
    @deck = Deck.featured
    @celebrities = Celebrity.all
    @card = Card.first
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def cards
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to Cards Against Inanity!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Cards Against Inanity"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper

  # return correct card suit for given card
  def suit_for(card)
    case card.face_suit
    when 1
      "hearts"
    when 2
      "clubs"
    when 3
      "diamonds"
    when 4
      "spades"
    when 5
      "joker"
    when 6
      "joker"
    else
      "unknown"
    end
  end

  # return correct card suit icon for given card
  def icon_char_for(card)
    case card.face_suit
    when 1
      "♥"
    when 2
      "♣"
    when 3
      "♦"
    when 4
      "♠"
    when 5
      "♣"
    when 6
      "♦"
    else
      "♠"
    end
  end

  # Return correct string character for face number for given card
  def face_number_for(card)
    case card.face_number
    when 1
      "A"
    when 2,3,4,5,6,7,8,9,10
      card.face_number.to_s
    when 11
      "J"
    when 12
      "Q"
    when 13
      "K"
    when 14
      ""
    else
      "?"
    end
  end

  def full_name_for(card)
    "#{card.lens_prefix} #{card.lens_name}"
  end

end

app/helpers/celebrities_helper.rb
module CelebritiesHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/generate.html.erb
<%= form_tag("/cards/generated.pdf", method: "get") do %>
  <%= label_tag(:whitecards, "White cards:") %>
  <%= text_area_tag(:whitecards, "Put your white cards here", class: "whiteta") %>
  <%= label_tag(:blackcards, "Black cards:") %>
  <%= text_area_tag(:blackcards, "Put your black cards here", class: "blackta") %>

  CARD SIZE
  <%= radio_button_tag(:cardsize, "S", checked: "true") %> Small (2"x2")
  <%= radio_button_tag(:cardsize, "L") %> Large (2.5"x3.5")
  <%= radio_button_tag(:cardsize, "LR") %> Large w/Round Corners (2.5"x3.5")

  <br>
  <br>
  <br>

  PAGE LAYOUT
  <%= radio_button_tag :pagelayout, "tiled", checked: "true" %> Tiled On 8.5"x11" Sheets
  <%= radio_button_tag :pagelayout, "oneperpage" %> One Card Per Page

  <br>
  <br>
  <br>

  ICON
  <%= radio_button_tag :icon, "default", checked: "true" %> Default

  <br>
  <br>
  <br>

  <%= submit_tag("Generate Cards") %>
<% end %>

app/views/cards/generator.html.erb
<br>
<%= form_tag("/cards/generated.pdf", multipart: true) do %>
  <%= label_tag(:whitecards, "CARDS:") %>
  <%= text_area_tag(:whitecards, "Put your cards here\n\nEach card on a new line", class: "whiteta", size: "25x10") %>
  <%= label_tag(:background_color, "Background Color:") %>
  <%= text_field_tag :background_color, nil, maxlength: 6, placeholder: 'ffffff' %>
  <%= label_tag(:text_color, "Text Color:") %>
  <%= text_field_tag :text_color, nil, maxlength: 6, placeholder: '000000' %>

  <br>
  <br>
  <b>Card Size:</b>
  <br>
  <%= label_tag nil, nil, class: "radio-inline" do %>
    <%= radio_button_tag(:cardsize, "S", checked: "true") %> Small (2"x2")
  <% end %>
  <%= label_tag nil, nil, class: "radio-inline" do %>
    <%= radio_button_tag(:cardsize, "L") %> Large (2.5"x3.5")
  <% end %>
  <%= label_tag nil, nil, class: "radio-inline" do %>
    <%= radio_button_tag(:cardsize, "LR") %> Large w/Round Corners (2.5"x3.5")
  <% end %>

  <br>
  <br>

  <b>Page Layout:</b>
  <br>
  <%= label_tag nil, nil, class: "radio-inline" do %>
    <%= radio_button_tag :pagelayout, "tiled", checked: "true" %> Tiled On 8.5"x11" Sheets
  <% end %>
  <%= label_tag nil, nil, class: "radio-inline" do %>
    <%= radio_button_tag :pagelayout, "oneperpage" %> One Card Per Page
  <% end %>

  <br>
  <br>

  <b>Bleed on individual cards (1/8"):</b>
  <br>
  <%= label_tag nil, nil, class: "radio-inline" do %>
    <%= radio_button_tag :bleed, "false", checked: "true" %> No Bleed
  <% end %>
  <%= label_tag nil, nil, class: "radio-inline" do %>
    <%= radio_button_tag :bleed, "true" %> Include Bleed
  <% end %>

  <br>
  <br>

  <b>DPI:</b>
  <br>
  <%= label_tag nil, nil, class: "radio-inline" do %>
    <%= radio_button_tag :dpi, "300", checked: "true" %> -dpi: 300
  <% end %>
  <%= label_tag nil, nil, class: "radio-inline" do %>
    <%= radio_button_tag :dpi, "600" %> -dpi: 600
  <% end %>
  <%= label_tag nil, nil, class: "radio-inline" do %>
    <%= radio_button_tag :dpi, "1200" %> -dpi: 1200
  <% end %>

  <br>
  <br>
  <br>

  <%= submit_tag("Generate Cards") %>

  <br>
  <br>
  <%= label_tag(:email, "Email:") %>
  <%= text_field_tag(:email) %>

  <%= submit_tag "Generate PNG", formaction: "/cards/generated" %>
<% end %>

app/views/cards/show.html.erb
<div class="row">
  <div class="col-sm-4">
    <%= render 'layouts/flippable_card' %>
  </div>
</div>

app/views/cards/test.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>cardExportTest</title>
    <%= stylesheet_link_tag "cards/cards" %>
    <style>
      body {margin:0;}
    </style>
  </head>

  <body>

    <div class="export-container">
      <%= render 'layouts/card' %>
    </div>

    <script type="text/javascript">
      var qcard = document.getElementsByClassName('qcard')[0];
      var qcardWidth = qcard.scrollWidth;
      qcard.style.fontSize = (qcardWidth / 26) + "px";
    </script>

  </body>
</html>

app/views/celebrities/random.html.erb
<style type="text/css">
  body {
    background-image: url(<%= asset_path 'dark-stone-repeating.jpg' %>);
  }
  .main-container {
    background-color: transparent;
  }
</style>

<div class="celebrities-random">
  <%= content_tag "div", id: "celebrities-data-div", data: {celebrities: @celebrities } do %>
  <% end %>

  <div class="row">
    <div class="col-sm-3">
      <div id="button-label">Suggest Famous Person</div>
      <button id="spin-button" type="button" class="">Click Me!</button>
    </div>
    <div class="col-sm-6">
      <%= render 'shared/slotmachine' %>
    </div>
    <div class="col-sm-3">
      <div class="celeb-display"></div>
    </div>
  </div>

</div>

app/views/decks/show.html.erb
<div class="decks-show">
  <div class="row deck-header-row">
    <div class="col-md-6 deck-header-name">
      <h1><%= @deck.name %></h1>
    </div>
    <div class="col-md-6 deck-header-buttons">
      <div class="deck-header-button-group">
        <div class="btn-group" id="card-list-filters" role="group" aria-label="...">
          <button type="button" class="btn btn-default" data-suit="hearts">
            ♥
          </button>
          <button type="button" class="btn btn-default" data-suit="clubs">
            ♣
          </button>
          <button type="button" class="btn btn-default" data-suit="diamonds">
            ♦
          </button>
          <button type="button" class="btn btn-default" data-suit="spades">
            ♠
          </button>
          <button type="button" class="btn btn-default" data-suit="joker">
            ♥
          </button>
        </div>
        <%= link_to "?", random_path, class: "btn btn-default", role: "button" %>
      </div>
    </div>
  </div>

  <div class="list-group" id="card-list">
    <% @deck.cards.card_ordered.each do |card| %>
      <%= link_to card_path(card), class: "list-group-item #{suit_for(card)}", data: { suit: suit_for(card) } do %>
        <%= face_number_for(card) %> <%= icon_char_for(card) %>
        <%= full_name_for(card) %>
      <% end %>
    <% end %>
  </div>

  <%= link_to "Find the Stupidest Card", sorting_game_deck_path(@deck) %>
</div>

app/views/decks/sorting_game.html.erb
<div class="decks-sortinggame">
  <%= content_tag "div", id: "card-data-div", data: {cards: @deck.cards.card_ordered } do %>
  <% end %>

  <h1>Stupidest Card Game</h1>

  <div class="row">
    <div class="col-sm-12" id="sg-instructions">
      Text to walk you through
    </div>
  </div>

  <div class="row" id="card-choices">
    <div class="col-sm-3">
      <div class="qcard2">
        card
      </div>
    </div>
    <div class="col-sm-3">
      <div class="qcard2">
        card
      </div>
    </div>
    <div class="col-sm-3">
      <div class="qcard2">
        card
      </div>
    </div>
    <div class="col-sm-3">
      <div class="qcard2">
        card
      </div>
    </div>
  </div>

  <!-- <div class="row">
    <div class="col-sm-12">
      <span>
        <button id="back-button" class="btn btn-primary" type="submit">Back</button>
        <button id="next-button" class="btn btn-primary" type="submit">Next</button>
      </span>
    </div>
  </div> -->
  <div class="footer navbar-fixed-bottom sg-buttons">
    <span>
      <button id="back-button" class="btn btn-primary" type="submit">Back</button>
      <button id="next-button" class="btn btn-primary" type="submit">Next</button>
    </span>
  </div>
</div>

app/views/games/teletype.html.erb
<div class="games-teletype">

  <%= content_tag "div", id: "celebrities-data-div", data: {celebrities: @celebrities } do %>
  <% end %>
  <%= content_tag "div", id: "card-data-div", data: {cards: @deck.cards.card_ordered } do %>
  <% end %>
  <%= audio_tag "typewriter-key-1.mp3", id: "typewriter-audio" %>

    <div class="teletype-input">
      <span class="start-game-button-span">
        <button id="start-game-button" class="btn btn-primary">Start Game</button>
      </span>
      <span class="question-choice-buttons">
        <button id="q1-button" class="btn btn-primary tt-q-button" type="submit">1</button>
        <button id="q2-button" class="btn btn-primary tt-q-button" type="submit">2</button>
        <button id="q3-button" class="btn btn-primary tt-q-button" type="submit">3</button>
      </span>
    </div>

  <div class="main">
    <div class="row">
    </div>
    <div class="row">
      <div class="col-sm-12">
        <div class="teletype-printout" id="teletype-screen"></div>
      </div>
    </div>
  </div>

</div>

app/views/games/who_am_i.html.erb
<style type="text/css">
  .main-container {
    background-color: transparent;
  }
</style>

<div class="games-whoami">
  <%= content_tag "div", id: "celebrities-data-div", data: {celebrities: @celebrities } do %>
  <% end %>
  <%= content_tag "div", id: "card-data-div", data: {cards: @deck.cards.card_ordered } do %>
  <% end %>

  <div class="intro-box">
    <div class="row">
      <div class="col-sm-12">
        <h4>Shall we play a game? <b>Who am I</b> is a guessing game - I'll think of a famous person, you guess who I am.</h4>
        <div class="debug-celeb-name">

        </div>
      </div>
    </div>
  </div>

  <div class="i-am-box">
    <div class="row">
      <div class="col-sm-12">
        <h2>I am <span id="whoami-blank">&nbsp;</span></h2>
      </div>
    </div>
  </div>

  <div class="replay-box">
    <div class="row">
      <div class="col-sm-12">
        <div id="game-over-message">
        </div>
        <p>Would you like to play again?</p>
      </div>
    </div>
  </div>

  <div class="spin-box">
    <div class="row">
      <div class="col-sm-3">
        <button id="spin-button" type="button" class="">Start Game!</button>
      </div>
      <div class="col-sm-9">
        <%= render 'shared/slotmachine' %>
      </div>
    </div>
  </div>

  <div class="qcard-hand">
    <div id="guess-feedback" class="row">
      <div class="col-sm-12">
        <p>I'm sorry, your guess is not correct.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <p>Pick a card with a question you'd like to ask me to help you figure out who I am.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-2 col-md-2 col-md-offset-1 col-sm-3">
        <%= render 'shared/empty_card' %>
      </div>
      <div class="col-lg-2 col-md-2 col-md-offset-0 col-sm-3 col-sm-offset-1">
        <%= render 'shared/empty_card' %>
      </div>
      <div class="col-lg-2 col-md-2 col-md-offset-0 col-sm-3 col-sm-offset-1">
        <%= render 'shared/empty_card' %>
      </div>
      <div class="col-lg-2 col-md-2 col-md-offset-0 col-sm-3 col-sm-offset-2">
        <%= render 'shared/empty_card' %>
      </div>
      <div class="col-lg-2 col-md-2 col-md-offset-0 col-sm-3 col-sm-offset-1">
        <%= render 'shared/empty_card' %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-2">
        <button type="button" class="btn btn-primary disabled" id="confirm-card-choice-button">Confirm</button>
      </div>
    </div>
  </div>

  <div class="qcard-answer-box">
    <div class="row">
      <div class="col-sm-4">
        <div class="player-guess-box">
          <p>Would you like to guess who I am? Type your guess in the box below. If you'd like to submit your guess, click "Submit Guess". If you're not yet sure who I am, click "Skip"</p>
          <input id="player-guess" type="text">
          <br>
          Wikipedia Results
          <br>
          <div class="wiki-search-results">
            Type a name in the search field above - if wikipedia has articles on that individual, links should appear here.
          </div>
          <button type="button" class="btn btn-primary" id="skip-guess-button">Skip</button>
          <button type="button" class="btn btn-primary disabled" id="submit-guess-button">Submit Guess</button>
        </div>
      </div>
      <div class="col-sm-8">
        <div id="interview-log">
        </div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/_card.html.erb
<div class="qcard">
  <div class="q-card-spacer">

  </div>
  <div class="q-card-content <%= suit_for(@card) %>">
    <div class="number-suit top left">
        <%= face_number_for(@card) %><br><%= icon_char_for(@card) %>
    </div>
    <!-- <div class="number-suit top right">
      <%= face_number_for(@card) %><br><%= icon_char_for(@card) %>
    </div>
    <div class="number-suit bottom left">
      <%= face_number_for(@card) %><br><%= icon_char_for(@card) %>
    </div> -->
    <div class="number-suit bottom right">
      <%= face_number_for(@card) %><br><%= icon_char_for(@card) %>
    </div>
    <div class="q-card-content-top">
      <div class="vertical-align" id="q-card-name">
        <h1>
          <%= @card.lens_name %>
        </h1>
      </div>
    </div>
    <div class="q-card-content-middle">
      <div class="" id="q-card-question">
        <p>
          <!-- Replace the following with something that pulls text from db -->
          Ask yourself:
        </p>
        <p>
          <%= @card.me_question %>
        </p>
      </div>
    </div>
    <div class="q-card-footer">
      Cards Against Inanity™ © 2018 Viral Virtue Inc.
    </div>
  </div>
</div>

app/views/layouts/_flippable_card.html.erb
<div class="card-container">
  <div class="card-container-spacer"></div>
  <div class="card-content-container">
    <div class="card-shell flippable">
      <div class="fcard flippable" onclick="this.classList.toggle('flipped');">
        <div class="front">
          <%= render 'layouts/card' %>
        </div>
        <div class="back">
          <div class="qback" style="background-image: url('<%= @card.image.url if @card.image? %>');"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Cards Against Inanity™ © 2017 Viral Virtue Inc.
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Cards Against Inanity", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Cards", cards_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<%= yield :page_specific_javascripts_before %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= yield :page_specific_javascripts_after %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
  </head>

  <body data-controller="<%= controller_name %>" data-action="<%= action_name %>">
    <%= render 'layouts/header' %>
    <div class="container main-container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_empty_card.html.erb
<div class="qcard">
  <!-- The following div is just to house the data-id attribute which will correspond to card id -->
  <div id="q-card-id" data-id=""></div>
  <div class="q-card-spacer">

  </div>
  <!-- The following div needs an additional class with the suit of the card -->
  <div class="q-card-content">
    <div class="number-suit top left">
        <!-- face_number<br>icon -->
    </div>
    <!-- <div class="number-suit top right">
      <%= face_number_for(@card) %><br><%= icon_char_for(@card) %>
    </div>
    <div class="number-suit bottom left">
      <%= face_number_for(@card) %><br><%= icon_char_for(@card) %>
    </div>
    <div class="number-suit bottom right">
      <%= face_number_for(@card) %><br><%= icon_char_for(@card) %>
    </div> -->
    <div class="q-card-content-top">
      <div class="vertical-align" id="q-card-name">
        <h1>
          <!-- card lens_name -->
        </h1>
      </div>
    </div>
    <div class="q-card-content-middle">
      <div class="one-third-align" id="q-card-question">
        <p>
          <!-- card me_question-->
        </p>
      </div>
    </div>
    <div class="q-card-footer">
      Cards Against Inanity™ © 2017 Viral Virtue Inc.
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<% content_for :page_specific_javascripts_after do %>
  <%= javascript_include_tag 'testdba', 'data-turbolinks-track': 'reload' %>
<% end %>
<h1>About</h1>
<p>This is the about page for Q54</p>
<p>About</p>
<p>About</p>
<p>About</p>
<p>About</p>
<p>About</p>
<p>About</p>
<p>About</p>
<p>About</p>

app/views/static_pages/cards.html.erb
<h1>An Example Card</h1>
<div class="row">
  <div class="card_outer col-md-4 col-md-offset-4 col-xs-10 col-xs-offset-1" style="background-color:grey;">
    <div class="card_inner">
      Hello
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>